/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {},
    },
    plugins: [require("daisyui")],
    daisyui: {
        themes: [
            {
                light: {
                    primary: "#3b82f6",
                    secondary: "#6b7280",
                    accent: "#8b5cf6",
                    neutral: "#1f2937",
                    "base-100": "#ffffff",
                    "base-200": "#f9fafb",
                    "base-300": "#f3f4f6",
                    info: "#06b6d4",
                    success: "#10b981",
                    warning: "#f59e0b",
                    error: "#ef4444",
                },
                dark: {
                    primary: "#60a5fa",
                    secondary: "#9ca3af",
                    accent: "#a78bfa",
                    neutral: "#374151",
                    "base-100": "#1f2937",
                    "base-200": "#374151",
                    "base-300": "#4b5563",
                    info: "#22d3ee",
                    success: "#34d399",
                    warning: "#fbbf24",
                    error: "#f87171",
                },
                modern: {
                    primary: "#8b5cf6",
                    secondary: "#a78bfa",
                    accent: "#ec4899",
                    neutral: "#0f172a",
                    "base-100": "#fafafa",
                    "base-200": "#f1f5f9",
                    "base-300": "#e2e8f0",
                    info: "#06b6d4",
                    success: "#22c55e",
                    warning: "#f59e0b",
                    error: "#f43f5e",
                },
                corporate: {
                    primary: "#1e40af",
                    secondary: "#64748b",
                    accent: "#0ea5e9",
                    neutral: "#1e293b",
                    "base-100": "#ffffff",
                    "base-200": "#f8fafc",
                    "base-300": "#f1f5f9",
                    info: "#0ea5e9",
                    success: "#059669",
                    warning: "#d97706",
                    error: "#dc2626",
                },
            },
        ],
        darkTheme: "dark",
        base: true,
        styled: true,
        utils: true,
        prefix: "",
        logs: true,
        themeRoot: ":root",
    },
};


